# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availavle',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='bramd',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=ecomapp.models.image_folder),
        ),
    ]
